### ISSUE TITLE
Missing media in SegmentModelAdmin

### ISSUE THREAD

**Issue by aweakley** [wagtail/wagtail-personalisation#194]
In our segment admin view at `/admin/wagtail_personalisation/segment/edit/1/` the page chooser in the Visit Count Rule does not pop up the modal because `wagtailadmin/js/page-chooser.js` and `wagtailadmin/js/page-chooser-modal.js` are missing from the media. 
I've fixed it by adding those files to `SegmentModelAdmin.form_view_extra_js`, but is there a better way?

**Comment by jberghoef** [comment]
The issue seems to have been caused by overriding the `extra_js` template block. #195 should fix this.

**Comment by aweakley** [comment]
That didn't fix it for me I'm afraid. I've pulled d9ef74c and I'm getting the same behaviour.
